/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BER_bbf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(735e0c24a3da61f838eab506425eba8e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rpi_iot/BER_bbf.h>
// pydoc.h is automatically generated in the build directory
#include <BER_bbf_pydoc.h>

void bind_BER_bbf(py::module& m)
{

    using BER_bbf    = ::gr::rpi_iot::BER_bbf;


    py::class_<BER_bbf, gr::block, gr::basic_block,
        std::shared_ptr<BER_bbf>>(m, "BER_bbf", D(BER_bbf))

        .def(py::init(&BER_bbf::make),
           py::arg("window_size"),
           py::arg("bps"),
           D(BER_bbf,make)
        )
        



        ;




}








