/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BPSK_Decoder_cb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1598fdb04586ec9430dff511f46eddbc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rpi_iot/BPSK_Decoder_cb.h>
// pydoc.h is automatically generated in the build directory
#include <BPSK_Decoder_cb_pydoc.h>

void bind_BPSK_Decoder_cb(py::module& m)
{

    using BPSK_Decoder_cb    = ::gr::rpi_iot::BPSK_Decoder_cb;


    py::class_<BPSK_Decoder_cb, gr::block, gr::basic_block,
        std::shared_ptr<BPSK_Decoder_cb>>(m, "BPSK_Decoder_cb", D(BPSK_Decoder_cb))

        .def(py::init(&BPSK_Decoder_cb::make),
           D(BPSK_Decoder_cb,make)
        )
        



        ;




}








