/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(QPSK_Decoder_cb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(54fd7f3c00ae072d79f01ced3db94891)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rpi_iot/QPSK_Decoder_cb.h>
// pydoc.h is automatically generated in the build directory
#include <QPSK_Decoder_cb_pydoc.h>

void bind_QPSK_Decoder_cb(py::module& m)
{

    using QPSK_Decoder_cb    = ::gr::rpi_iot::QPSK_Decoder_cb;


    py::class_<QPSK_Decoder_cb, gr::block, gr::basic_block,
        std::shared_ptr<QPSK_Decoder_cb>>(m, "QPSK_Decoder_cb", D(QPSK_Decoder_cb))

        .def(py::init(&QPSK_Decoder_cb::make),
           D(QPSK_Decoder_cb,make)
        )
        



        ;




}








